name: Bump casks on schedule or request

on:
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    # Every 3 hours 23 minutes past the hour
    - cron: "23 */3 * * *"

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  autobump:
    if: github.repository == 'zhiyue/homebrew-mytap'
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: false
          cask: true
          test-bot: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Get list of autobump casks
        id: autobump
        run: |
          REPO="zhiyue/mytap"
          CASKS=$(xargs < "$(brew --repo $REPO)"/.github/autobump.txt)
          PREFIXED_CASKS=""
          for cask in $CASKS; do
            if [ -n "$PREFIXED_CASKS" ]; then
              PREFIXED_CASKS="$PREFIXED_CASKS $REPO/$cask"
            else
              PREFIXED_CASKS="$REPO/$cask"
            fi
          done
          echo "调试信息 - 原始 CASKS: $CASKS"
          echo "调试信息 - 带前缀的 PREFIXED_CASKS: $PREFIXED_CASKS"
          echo "autobump_list=$PREFIXED_CASKS" >> "$GITHUB_OUTPUT"
          echo "调试信息 - 最终设置的 autobump_list: $PREFIXED_CASKS"

      - name: Bump casks
        run: |
          brew bump --full-name --no-fork --tap "zhiyue/homebrew-mytap" --open-pr --cask --debug
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
          HOMEBREW_GITHUB_PACKAGES_USER: "zhiyue"
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_CASK_REPO_WORKFLOW_TOKEN || github.token }}
          HOMEBREW_DEVELOPER: "1"
      
